import { CMS_DOCS } from '../../../lib/cms';
import {
  initialProject,
  initialCertificate,
  initialSkillGroup,
  initialExperienceItem,
  initialResource,
  initialBlogPost,
  initialTestimonial,
  initialService,
  initialOpenSource,
} from './adminConstants';
import { Folder, Award, Wrench, Link as LinkIcon, Sparkles, BookOpen, Quote, Briefcase, Github } from 'lucide-react';

export const projectFields = [
  { key: 'missionCode', label: 'Mission Code', type: 'text', group: 'summary', placeholder: 'e.g. STUDYOS' },
  { key: 'year', label: 'Year', type: 'number', group: 'summary', placeholder: 'e.g. 2026' },
  { key: 'title', label: 'Title', type: 'text', group: 'summary', placeholder: 'e.g. StudyOS' },
  { key: 'shortDescription', label: 'Short Description (5-second intro)', type: 'textarea', group: 'summary', placeholder: 'e.g. AI-powered study operating system that helps students organize notes, generate flashcards, and automate learning.' },
  { key: 'tech', label: 'Tech Stack Tags', type: 'list', placeholder: 'Enter a tech (e.g. Next.js, React, Supabase)', group: 'summary' },
  { key: 'category', label: 'Category', type: 'text', group: 'summary', placeholder: 'e.g. Web Apps / Productivity' },
  {
    key: 'status',
    label: 'Status',
    type: 'select',
    options: ['Draft', 'In progress', 'Live', 'Archived'],
    group: 'summary',
  },
  { key: 'client', label: 'Client / Company', type: 'text', group: 'summary', placeholder: 'e.g. StudyOS Inc. / Personal Research' },
  { key: 'industry', label: 'Industry', type: 'text', group: 'summary', placeholder: 'e.g. EdTech / SaaS / productivity' },
  { key: 'teamSize', label: 'Team Size', type: 'text', group: 'summary', placeholder: 'e.g. Sole Developer / 3 engineers' },
  { key: 'projectTimeline', label: 'Timeline / Duration', type: 'text', group: 'summary', placeholder: 'e.g. 3 Months (Spring 2026)' },
  { key: 'outcomeBadge', label: 'Outcome Badge (Metrics Callout)', type: 'text', group: 'summary', placeholder: 'e.g. Reduced loading lag by 40%' },
  { key: 'featured', label: 'Featured Project', type: 'checkbox', group: 'summary' },
  { key: 'completed', label: 'Completed Project Status', type: 'checkbox', group: 'summary' },
  {
    key: 'projectType',
    label: 'Project Context Type',
    type: 'select',
    options: ['personal', 'client'],
    group: 'summary',
  },
  { key: 'isPrivate', label: 'Private Code / Private Repository', type: 'checkbox', group: 'summary' },
  { key: 'description', label: 'Case Study Description (Overview)', type: 'markdown', group: 'story', placeholder: 'Provide a detailed summary description of this case study.' },
  { key: 'role', label: 'Your Specific Role', type: 'text', group: 'story', placeholder: 'e.g. Lead Full-Stack Architect & UI Designer' },
  { key: 'problem', label: 'Problem Statement', type: 'textarea', group: 'story', placeholder: 'e.g. Students use multiple disconnected platforms for notes, calendars, and tasks, causing cognitive load.' },
  { key: 'solution', label: 'Proposed Solution', type: 'textarea', group: 'story', placeholder: 'e.g. StudyOS centralizes study tasks, document summaries, and flashcards into one unified AI workspace.' },
  { key: 'architecture', label: 'Architecture (ASCII Text Fallback)', type: 'markdown', group: 'story', placeholder: 'Use this text area only if you do not upload an Architecture Image diagram.' },
  { key: 'features', label: 'Key Features List', type: 'list', placeholder: 'e.g. Automatic flashcard generation / Spaced repetition algorithm', group: 'story' },
  { key: 'learned', label: 'What I Learned (Lessons Learned Reflection)', type: 'textarea', group: 'story', placeholder: 'Explain key technical growth, prompt engineering, and architecture takeaways.' },
  { key: 'lessonsLearned', label: 'Alternative Lessons learned', type: 'textarea', group: 'story', placeholder: 'Reflection notes.' },
  { key: 'nextSteps', label: 'Next Steps & Future Roadmaps', type: 'textarea', group: 'story', placeholder: 'e.g. Integrating offline vector syncing and real-time collaboration.' },
  { key: 'challenges', label: 'Engineering Challenges', type: 'textarea', group: 'story', placeholder: 'e.g. Optimizing OpenAI token costs for large document processing.' },
  { key: 'outcomes', label: 'Business & User Outcomes', type: 'textarea', group: 'story', placeholder: 'e.g. Increased student study consistency metrics by 25%.' },
  {
    key: 'impactMetricsJson',
    label: 'Impact Metrics Data Grid',
    type: 'object-list',
    group: 'metrics',
    createItem: () => ({ label: '', value: '', suffix: '' }),
    fields: [
      { key: 'label', label: 'Label (e.g. Screens designed)', type: 'text', placeholder: 'e.g. AI Features Built' },
      { key: 'value', label: 'Value (e.g. 45)', type: 'text', placeholder: 'e.g. 12' },
      { key: 'suffix', label: 'Suffix (e.g. +)', type: 'text', placeholder: 'e.g. +' },
    ],
  },
  { key: 'github', label: 'GitHub Repo URL', type: 'text', group: 'links', placeholder: 'https://github.com/...' },
  { key: 'external', label: 'Live Demo URL', type: 'text', group: 'links', placeholder: 'https://studyos.com' },
  { key: 'demoEmail', label: 'Demo Email Credentials', type: 'text', group: 'links', placeholder: 'e.g. demo@studyos.com' },
  { key: 'demoPassword', label: 'Demo Password Credentials', type: 'text', group: 'links', placeholder: 'e.g. studyos123' },
  { key: 'perfScore', label: 'Lighthouse Performance Score (0-100)', type: 'text', group: 'metrics', placeholder: 'e.g. 98' },
  { key: 'accessScore', label: 'Lighthouse Accessibility Score (0-100)', type: 'text', group: 'metrics', placeholder: 'e.g. 100' },
  { key: 'bestScore', label: 'Lighthouse Best Practices Score (0-100)', type: 'text', group: 'metrics', placeholder: 'e.g. 100' },
  { key: 'seoScore', label: 'Lighthouse SEO Score (0-100)', type: 'text', group: 'metrics', placeholder: 'e.g. 100' },
  { key: 'sandboxUrl', label: 'Live Code Sandbox URL', type: 'text', group: 'links', placeholder: 'e.g. StackBlitz embed link' },
  { key: 'videoUrl', label: 'Video Preview URL (mp4/webm file link)', type: 'text', group: 'media', placeholder: 'https://...' },
  { key: 'videoCaption', label: 'Video Caption', type: 'text', group: 'media', placeholder: 'e.g. StudyOS core application interface walkthrough' },
  { key: 'thumbnail', label: 'Thumbnail Image File', type: 'image', group: 'media' },
  { key: 'architectureImage', label: 'Architecture Diagram Image File', type: 'image', group: 'media' },
  {
    key: 'documents',
    label: 'Documents & Presentations',
    type: 'object-list',
    group: 'media',
    helper: 'Upload PDFs, slide decks, or text documents (click upload icon).',
    createItem: () => ({ url: '', name: '' }),
    fields: [
      { key: 'url', label: 'File URL', type: 'file' },
      { key: 'name', label: 'Document Name', type: 'text', placeholder: 'e.g. Pitch Deck' },
    ],
  },
  {
    key: 'screenshots',
    label: 'Screenshots & motion',
    type: 'object-list',
    group: 'media',
    helper: 'URL, optional caption for the modal gallery, and alt text for accessibility.',
    createItem: () => ({ url: '', caption: '', alt: '' }),
    fields: [
      { key: 'url', label: 'Image or video URL', type: 'image' },
      { key: 'caption', label: 'Caption', type: 'text' },
      { key: 'alt', label: 'Alt text', type: 'text' },
    ],
  },
];

export const certificateFields = [
  { key: 'title', label: 'Title', type: 'text', group: 'identity' },
  { key: 'issuer', label: 'Issuer', type: 'text', group: 'identity' },
  { key: 'date', label: 'Date', type: 'text', group: 'identity' },
  { key: 'credential', label: 'Credential', type: 'text', group: 'identity' },
  { key: 'link', label: 'Verification Link', type: 'text', group: 'identity' },
  { key: 'category', label: 'Category', type: 'select', group: 'identity',
    options: ['Cloud', 'Data', 'Programming', 'Networking', 'Microsoft', 'AWS', 'Security', 'DevOps', 'AI/ML', 'Other'] },
  { key: 'featured', label: 'Featured (show on portfolio homepage)', type: 'checkbox', group: 'identity' },
  { key: 'skills', label: 'Skills', type: 'list', placeholder: 'Enter a skill', group: 'identity' },
  { key: 'durationHours', label: 'Course Duration (Hours)', type: 'number', group: 'identity' },
  { key: 'image', label: 'Badge / Logo Image', type: 'image', group: 'media', aspect: null },
  { key: 'pdfUrl', label: 'Certificate PDF', type: 'pdf', group: 'media', accept: 'application/pdf,.pdf' },
];

export const skillFields = [
  { key: 'title', label: 'Group Title', type: 'text', group: 'summary' },
  { key: 'order', label: 'Order', type: 'number', group: 'summary' },
  {
    key: 'skillsJson',
    label: 'Skills',
    type: 'object-list',
    group: 'skills',
    createItem: () => ({ name: '', level: 0, proficiency: '', rationale: '', iconUrl: '' }),
    fields: [
      { key: 'name', label: 'Skill Name', type: 'text' },
      { key: 'level', label: 'Level (%)', type: 'number' },
      {
        key: 'proficiency',
        label: 'Proficiency',
        type: 'select',
        options: ['Beginner', 'Intermediate', 'Proficient', 'Advanced', 'Expert'],
      },
      { key: 'iconUrl', label: 'Icon / Image URL', type: 'image' },
      { key: 'rationale', label: 'Rationale', type: 'textarea' },
    ],
  },
];

export const resourceFields = [
  { key: 'title', label: 'Title', type: 'text', group: 'resourceMeta' },
  { key: 'type', label: 'Resource Type', type: 'select', group: 'resourceMeta',
    options: ['Link', 'PDF', 'Document', 'Image', 'Video', 'Tool', 'Cheat Sheet', 'Template', 'Other'] },
  { key: 'category', label: 'Category', type: 'text', placeholder: 'e.g. Design, DevOps, AI…', group: 'resourceMeta' },
  { key: 'author', label: 'Author / Source', type: 'text', placeholder: 'e.g. Google, MDN, your name…', group: 'resourceMeta' },
  { key: 'date', label: 'Date Added', type: 'text', placeholder: 'YYYY-MM-DD', group: 'resourceMeta' },
  { key: 'featured', label: 'Featured (pin to top)', type: 'checkbox', group: 'resourceMeta' },
  { key: 'description', label: 'Description', type: 'textarea', group: 'resourceContent' },
  { key: 'url', label: 'External URL (for links / references)', type: 'text', placeholder: 'https://…', group: 'resourceContent' },
  { key: 'fileUrl', label: 'Upload File (PDF, Doc, Image, Video)', type: 'file', group: 'resourceMedia',
    accept: 'application/pdf,.pdf,.doc,.docx,image/*,video/*' },
  { key: 'thumbnail', label: 'Thumbnail / Preview Image', type: 'image', group: 'resourceMedia', aspect: null },
];

export const blogFields = [
  { key: 'slug', label: 'Slug', type: 'text', group: 'meta' },
  { key: 'title', label: 'Title', type: 'text', group: 'meta' },
  { key: 'excerpt', label: 'Excerpt', type: 'textarea', group: 'meta' },
  { key: 'tags', label: 'Tags', type: 'list', placeholder: 'Enter a tag', group: 'meta' },
  { key: 'category', label: 'Category', type: 'text', group: 'meta' },
  { key: 'status', label: 'Status', type: 'select', options: ['Draft', 'Published'], group: 'meta' },
  { key: 'date', label: 'Publish Date', type: 'text', group: 'meta' },
  { key: 'readTime', label: 'Read Time', type: 'text', group: 'meta' },
  { key: 'featured', label: 'Featured Post', type: 'checkbox', group: 'meta' },
  { key: 'body', label: 'Body', type: 'markdown', group: 'content' },
  { key: 'codeSnippet', label: 'Code Snippet', type: 'markdown', group: 'content' },
  { key: 'language', label: 'Language', type: 'text', group: 'content' },
  { key: 'link', label: 'Canonical/External Link', type: 'text', group: 'links' },
];

export const testimonialFields = [
  { key: 'name', label: 'Name', type: 'text', group: 'author' },
  { key: 'role', label: 'Role', type: 'text', group: 'author' },
  { key: 'company', label: 'Company', type: 'text', group: 'author' },
  { key: 'content', label: 'Quote', type: 'textarea', group: 'testimonialBody' },
  { key: 'rating', label: 'Rating', type: 'number', group: 'testimonialBody' },
  { key: 'context', label: 'Context', type: 'text', group: 'testimonialBody' },
  { key: 'link', label: 'Link', type: 'text', group: 'testimonialBody' },
];

export const serviceFields = [
  { key: 'title',    label: 'Title',    type: 'text',   group: 'serviceOffer' },
  { key: 'status',   label: 'Status',   type: 'select', options: ['Draft', 'Published'], group: 'serviceOffer' },
  { key: 'category', label: 'Category', type: 'select',
    options: ['Web Development', 'Mobile Development', 'UI/UX Design', 'API & Backend', 'Consulting', 'Data & Analytics', 'DevOps', 'Other'],
    group: 'serviceOffer' },
  { key: 'icon',     label: 'Icon name (Lucide)', type: 'text', placeholder: 'e.g. Globe, Code2, Layers, Cpu, BarChart2…', group: 'serviceOffer' },
  { key: 'summary',  label: 'Summary (card pitch)',  type: 'textarea', group: 'serviceOffer' },
  { key: 'featured', label: 'Featured (show on homepage)', type: 'checkbox', group: 'serviceOffer' },
  { key: 'availability', label: 'Availability', type: 'select',
    options: ['Available now', 'Limited availability', 'Booking soon', 'Waitlist only', 'Unavailable'],
    group: 'serviceOffer' },
  { key: 'idealFor', label: 'Ideal for (target clients)', type: 'text',
    placeholder: 'e.g. Startups, E-commerce, SMEs, Agencies', group: 'serviceOffer' },
  { key: 'startingPrice', label: 'Starting Price (LKR)', type: 'text',
    placeholder: 'e.g. From Rs. 15,000 / Rs. 8,000–25,000', group: 'serviceDelivery' },
  { key: 'timeline',   label: 'Typical Timeline', type: 'text', placeholder: 'e.g. 2–4 weeks',         group: 'serviceDelivery' },
  { key: 'turnaround', label: 'Turnaround',        type: 'text', placeholder: 'e.g. 48 hr first draft', group: 'serviceDelivery' },
  { key: 'scope',        label: 'Scope description', type: 'textarea', group: 'serviceDelivery' },
  { key: 'deliverables', label: 'Deliverables',       type: 'textarea', group: 'serviceDelivery' },
  { key: 'features',     label: "What's included (checklist)", type: 'list',
    placeholder: 'e.g. Responsive design, Source code delivery, 2 revisions…', group: 'serviceDelivery' },
  {
    key: 'processSteps',
    label: 'Process Steps (how you work)',
    type: 'object-list',
    group: 'serviceProcess',
    createItem: () => ({ step: '', description: '' }),
    fields: [
      { key: 'step',        label: 'Step name',        type: 'text', placeholder: 'e.g. Discovery' },
      { key: 'description', label: 'Short description', type: 'text', placeholder: 'e.g. We discuss goals and scope' },
    ],
  },
  {
    key: 'templates',
    label: 'Service Templates (optional)',
    type: 'object-list',
    group: 'serviceProcess',
    createItem: () => ({ name: '', description: '', demoUrl: '', imageUrl: '', vibe: '' }),
    fields: [
      { key: 'name',        label: 'Template Name',     type: 'text', placeholder: 'e.g. Minimal & Clean' },
      { key: 'vibe',        label: 'Style / Vibe',      type: 'text', placeholder: 'e.g. Clean typography, light mode' },
      { key: 'description', label: 'Brief description', type: 'text', placeholder: 'e.g. Best for writers and minimal engineers' },
      { key: 'demoUrl',     label: 'Live Demo URL',     type: 'text', placeholder: 'https://demo-minimal.me' },
      { key: 'imageUrl',    label: 'Preview Image URL', type: 'image' },
    ],
  },
  { key: 'cta',            label: 'CTA button label',        type: 'text', placeholder: "e.g. Let's build this, Get a quote", group: 'serviceDelivery' },
  { key: 'link',           label: 'CTA link / Booking URL',  type: 'text', placeholder: 'https://cal.com/… or /#contact',      group: 'serviceDelivery' },
  { key: 'relatedProject', label: 'Related project title',   type: 'text', placeholder: 'e.g. StudyOS — links to /projects',    group: 'serviceDelivery' },
  { key: 'tags', label: 'Tech stack tags', type: 'list', placeholder: 'e.g. React, Firebase, TypeScript', group: 'serviceDelivery' },
];

export const openSourceFields = [
  { key: 'name', label: 'Project Name', type: 'text', group: 'identity' },
  { key: 'description', label: 'Description', type: 'textarea', group: 'identity' },
  { key: 'repository', label: 'Repository URL', type: 'text', group: 'identity' },
  { key: 'category', label: 'Category', type: 'text', group: 'identity' },
  { key: 'status', label: 'Status', type: 'text', group: 'identity' },
  { key: 'stars', label: 'Stars', type: 'number', group: 'stats' },
  { key: 'forks', label: 'Forks', type: 'number', group: 'stats' },
  { key: 'watchers', label: 'Watchers', type: 'number', group: 'stats' },
];

export const experienceFields = [
  { key: 'type', label: 'Type', type: 'text', group: 'role' },
  { key: 'title', label: 'Title', type: 'text', group: 'role' },
  { key: 'organization', label: 'Organization', type: 'text', group: 'role' },
  { key: 'location', label: 'Location', type: 'text', group: 'role' },
  { key: 'period', label: 'Period', type: 'text', group: 'role' },
  { key: 'description', label: 'Description', type: 'textarea', group: 'detail' },
  { key: 'skills', label: 'Skills', type: 'list', placeholder: 'Enter a skill', group: 'detail' },
];

export const COLLECTION_FIELD_GROUPS = {
  summary: {
    label: 'Summary & classification',
    hint: 'What appears on cards, filters, and list views.',
  },
  story: {
    label: 'Case study & narrative',
    hint: 'Long-form content shown in the project modal.',
  },
  metrics: { label: 'Impact metrics', hint: 'Optional headline numbers.' },
  links: { label: 'Outbound links', hint: 'Demo and source URLs.' },
  media: { label: 'Media', hint: 'Thumbnails, GIFs, and screenshots.' },
  meta: {
    label: 'Metadata & publishing',
    hint: 'Slug, dates, categories, and flags.',
  },
  content: { label: 'Article body', hint: 'Main text and optional code block.' },
  identity: { label: 'Basics', hint: 'Names, titles, and verification.' },
  stats: { label: 'Repository stats', hint: 'Stars, forks, and watchers.' },
  skills: { label: 'Skill entries', hint: 'Cards inside this group.' },
  resourceMeta: { label: 'Listing', hint: 'How this resource appears in lists.' },
  resourceLink: { label: 'URL & description', hint: 'Link target and optional blurb.' },
  author: { label: 'Author', hint: 'Who the testimonial is from.' },
  testimonialBody: { label: 'Quote & details', hint: 'Quote text, rating, and references.' },
  serviceOffer:    { label: 'Offer headline',     hint: 'Title, category, icon, pitch, and availability.' },
  serviceDelivery: { label: 'Scope & delivery',   hint: 'Pricing (LKR), timeline, features, CTA, and tech tags.' },
  serviceProcess:  { label: 'Process steps',      hint: 'Numbered workflow shown on the service card.' },
  role: { label: 'Role & place', hint: 'Title, organization, location, and timeframe.' },
  detail: { label: 'Story & skills', hint: 'Description and skill tags.' },
  general: { label: 'Fields', hint: '' },
};

export const sectionConfig = {
  [CMS_DOCS.projects]: {
    title: 'Projects',
    icon: Folder,
    collectionKey: 'items',
    initialItem: initialProject,
    uploadFolder: 'projects',
    help: 'Manage portfolio projects, case-study content, and quick links.',
  },
  [CMS_DOCS.certifications]: {
    title: 'Certificates',
    icon: Award,
    collectionKey: 'items',
    initialItem: initialCertificate,
    uploadFolder: 'certificates',
    help: 'Manage certs, issuers, and verification links.',
  },
  [CMS_DOCS.skills]: {
    title: 'Skills',
    icon: Wrench,
    collectionKey: 'items',
    initialItem: initialSkillGroup,
    uploadFolder: null,
    help: 'Manage skill groups with card-style skill details.',
  },
  [CMS_DOCS.experience]: {
    title: 'Experience',
    icon: Sparkles,
    collectionKey: 'items',
    initialItem: initialExperienceItem,
    uploadFolder: null,
    help: 'Manage work history and education entries shown on the timeline.',
  },
  [CMS_DOCS.resources]: {
    title: 'Resources',
    icon: LinkIcon,
    collectionKey: 'items',
    initialItem: initialResource,
    uploadFolder: 'resources',
    help: 'Manage external links, docs, and resource pages.',
  },
  [CMS_DOCS.blog]: {
    title: 'Blog',
    icon: BookOpen,
    collectionKey: 'items',
    initialItem: initialBlogPost,
    uploadFolder: null,
    help: 'Manage articles, tutorials, and case studies.',
  },
  [CMS_DOCS.testimonials]: {
    title: 'Testimonials',
    icon: Quote,
    collectionKey: 'items',
    initialItem: initialTestimonial,
    uploadFolder: null,
    help: 'Manage peer, mentor, and client recommendations.',
  },
  [CMS_DOCS.services]: {
    title: 'Services',
    icon: Briefcase,
    collectionKey: 'items',
    initialItem: initialService,
    uploadFolder: null,
    help: 'Manage your freelance offerings and delivery scope.',
  },
  [CMS_DOCS.openSource]: {
    title: 'Open Source',
    icon: Github,
    collectionKey: 'items',
    initialItem: initialOpenSource,
    uploadFolder: null,
    help: 'Manage your external OSS packages and contributions.',
  },
};
